# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric: https://fabricmc.net/develop
# Alineado con rama 1.21.1 de https://github.com/FabricMC/fabric-example-mod
minecraft_version=1.21.1
loader_version=0.18.6
loom_version=1.15-SNAPSHOT

mod_version=0.1.0-dev
maven_group=com.team_aether

fabric_api_version=0.116.10+1.21.1

kotlin_version=2.1.0
fabric_kotlin_version=1.13.0+kotlin.2.1.0

# Cobblemon (Modrinth Maven). Cambia el id si usas otra versión.
cobblemon_modrinth_version=kF7CvxTo
